### ISSUE TITLE
Remove deprecated functions

### ISSUE THREAD

**Issue by njh** [njh/twolame#74]
* DLL_EXPORT int twolame_set_VBR_q(twolame_options * glopts, float level);
* DLL_EXPORT float twolame_get_VBR_q(twolame_options * glopts);

Does this require incrementing the major version number?

**Comment by eblanca** [comment]
I would avoid API changes before 0.4.0 because this would require a change in major number too.
Rather, this may be evaluated after 0.4.x, when we'll also see the impact a float-only encoding core may have (which is still in progress in a non-dead branch of my git repo).
In short, delay the "big changes" after this upcoming 0.4.x branch.

**Comment by njh** [comment]
Yes, I assigned it to the 1.0 milestone for this reason.

**Comment by njh** [comment]
Functions removed in 45e78bd8be2daa5873e39bdf588c3f2070ef4d48
